RUN echo '#!/bin/bash' > /usr/local/bin/inf-tak \
    && echo 'case "$1" in' >> /usr/local/bin/inf-tak \
    && echo '    update)' >> /usr/local/bin/inf-tak \
    && echo '        echo "Atualizando os repositórios..."' >> /usr/local/bin/inf-tak \
    && echo '        apt-get update' >> /usr/local/bin/inf-tak \
    && echo '        ;;' >> /usr/local/bin/inf-tak \
    && echo '    steel)' >> /usr/local/bin/inf-tak \
    && echo '        echo "Instalando $2..."' >> /usr/local/bin/inf-tak \
    && echo '        apt-get update && apt-get install -y $2' >> /usr/local/bin/inf-tak \
    && echo '        ;;' >> /usr/local/bin/inf-tak \
    && echo '    *)' >> /usr/local/bin/inf-tak \
    && echo '        echo "Comando desconhecido: $1"' >> /usr/local/bin/inf-tak \
    && echo '        ;;' >> /usr/local/bin/inf-tak \
    && echo 'esac' >> /usr/local/bin/inf-tak

# Torne o script executável
RUN chmod +x /usr/local/bin/inf-tak

# Adicione comandos personalizados creader e filow
RUN echo '#!/bin/bash\nmkdir "$@"' > /usr/local/bin/creader \
    && chmod +x /usr/local/bin/creader \
    && echo '#!/bin/bash\ntouch "$@"' > /usr/local/bin/filow \
    && chmod +x /usr/local/bin/filow
